[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
# fs_permissions = [{ access = "read", path = "./" }]
fs_permissions = [
    { access = "read", path = "src/utils/JsonBindings.sol" },
    # { access = "read", path = "utils/JsonBindings.sol" },
    # { access = "read", path = "lib/aave-v4/tests/helpers/mocks/JsonBindings.sol" },
    # { access = "read", path = "./config" },
    # { access = "read", path = "./out" },
    # { access = "read-write", path = "./output" },
]
skip = ["tests/helpers/mocks/JsonBindings.sol"]

[bind_json]
out = "src/utils/JsonBindings.sol"
include = ["src/utils/EIP712TypesLocal.sol"]

remappings = [
    "aave-v4/=lib/aave-v4/",
    "forge-std/=lib/forge-std/src/",
    # resolve aave-v4 internal `src/` folder
    "src/dependencies/=lib/aave-v4/src/dependencies/",
    "src/interfaces/=lib/aave-v4/src/interfaces/",
    "src/hub/=lib/aave-v4/src/hub/",
    "src/spoke/=lib/aave-v4/src/spoke/",
    "tests/=lib/aave-v4/tests/",
]

[rpc_endpoints]
mainnet = "https://ethereum.reth.rs/rpc"
